export const links = {
    auth: {
        signIn: '/auth/sign-in',
        signUp: '/auth/sign-up',
        verifyEmail: '/auth/verify-email',
        emailVerificationPending: '/auth/email-verification-pending',
        forgotPassword: '/auth/forgot-password',
        resetPassword: '/auth/reset-password',
        acceptInvitation: '/auth/accept-invitation',
    },
    dashboard: {
        index: '/dashboard',
        profile: '/dashboard/profile',
        settings: '/dashboard/settings',
        changePassword: '/dashboard/change-password',
        lessons: '/dashboard/lessons',
        shop: '/dashboard/shop',
        wallet: '/dashboard/wallet',
        movies: '/dashboard/movies',
        orders: '/dashboard/orders',
        organizations: '/dashboard/organizations',
        organization: {
            list: "/dashboard/organizations",
            create: "/dashboard/organizations/create",
            inviteMember: "/dashboard/organizations/invite",
            members: "/dashboard/organizations/members",
            invitations: "/dashboard/organizations/invitations",
        },
        createOrganization: '/dashboard/organizations/create',
        inviteMember: '/dashboard/organizations/invite',
    },
} as const;