export const AppRoutes = {
    auth: {
        signIn: "/auth/sign-in",
        signUp: "/auth/sign-up",
        verifyEmail: "/auth/verify-email",
        emailVerificationPending: "/auth/email-verification-pending",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password",
    },
    org: {
        dashboard: {
            index: "/dashboard",
            profile: "/dashboard/profile",
            sessions: "/dashboard/sessions",
            settings: "/dashboard/settings",
            changePassword: "/dashboard/change-password",
            lessons: "/dashboard/lessons",
            lessonStudy: (lessonId: string) => `/dashboard/lessons/${lessonId}`,
            playlistDetail: (playlistId: string | number) => `/dashboard/playlists/${playlistId}`,
            mySchedule: "/dashboard/my-schedule",
            vocabulary: "/dashboard/vocabulary",
            shop: "/dashboard/shop",
            wallet: "/dashboard/wallet",
            movies: "/dashboard/movies",
            orders: "/dashboard/orders",
        },
        admin: {
            index: "/admin",
            media: "/admin/media",
            playlists: "/admin/playlists",
            playlistDetail: (id: string | number) => `/admin/playlists/${id}`,
            invitations: "/admin/invitations",
            members: "/admin/members",
            analytics: "/admin/analytics",
            schedule: "/admin/schedule",
            uploads: "/admin/uploads",
            bulk: "/admin/bulk",
            billing: {
                index: "/admin/billing",
                accounts: "/admin/billing/accounts",
                transactions: "/admin/billing/transactions",
                plans: "/admin/billing/plans",
            },
            organizations: "/admin/organizations",
        },
        teaching: {
            index: "/teaching",
            lessons: "/teaching/lessons",
            lessonPreview: (lessonId: string) => `/teaching/lessons/${lessonId}/preview`,
            media: "/teaching/media",
            playlists: "/teaching/playlists",
            playlistDetail: (id: string | number) => `/teaching/playlists/${id}`,
            textLibrary: "/teaching/text-library",
            textLibraryImport: "/teaching/text-library/import",
            textLibraryImportReview: (jobId: string) =>
                `/teaching/text-library/import/${jobId}/review`,
            sessions: "/teaching/sessions",
            schedule: "/teaching/sessions",
            students: "/teaching/students",
            vocabulary: "/teaching/vocabulary",
        },
    },
    admin: {
        index: "/admin",
        users: "/admin/users",
        emails: "/admin/emails",
        organizations: "/admin/organizations",
        billing: "/admin/billing",
        auditLogs: "/admin/audit-logs",
    },
    onboarding: {
        index: "/onboarding",
        noOrganization: "/onboarding/no-organization",
        selectOrganization: "/onboarding/select-organization",
        acceptInvitation: "/onboarding/accept-invitation",
    },
    unauthorized: "/unauthorized",
    notFound: "/404",
} as const;
