export const AppRoutes = {
    auth: {
        signIn: "/auth/sign-in",
        signUp: "/auth/sign-up",
        verifyEmail: "/auth/verify-email",
        emailVerificationPending: "/auth/email-verification-pending",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password",
    },
    org: {
        dashboard: {
            index: "/dashboard",
            profile: "/dashboard/profile",
            sessions: "/dashboard/sessions",
            settings: "/dashboard/settings",
            changePassword: "/dashboard/change-password",
            lessons: "/dashboard/lessons",
            shop: "/dashboard/shop",
            wallet: "/dashboard/wallet",
            movies: "/dashboard/movies",
            orders: "/dashboard/orders",
        },
        admin: {
            index: "/admin",
            media: "/admin/media",
            playlists: "/admin/playlists",
            playlistDetail: (id: string | number) => `/admin/playlists/${id}`,
            invitations: "/admin/invitations",
            members: "/admin/members",
            analytics: "/admin/analytics",
            schedule: "/admin/schedule",
            uploads: "/admin/uploads",
            bulk: "/admin/bulk",
            finance: {
                index: "/admin/finance",
                accounts: "/admin/finance/accounts",
                transactions: "/admin/finance/transactions",
            },
            organizations: "/admin/organizations",
        },
        teaching: {
            index: "/teaching",
            media: "/teaching/media",
            playlists: "/teaching/playlists",
            playlistDetail: (id: string | number) => `/teaching/playlists/${id}`,
            schedule: "/teaching/schedule",
            students: "/teaching/students",
        },
    },
    admin: {
        index: "/admin",
        users: "/admin/users",
        emails: "/admin/emails",
        organizations: "/admin/organizations",
        financial: "/admin/financial",
    },
    onboarding: {
        index: "/onboarding",
        noOrganization: "/onboarding/no-organization",
        selectOrganization: "/onboarding/select-organization",
        acceptInvitation: "/onboarding/accept-invitation",
    },
    unauthorized: "/unauthorized",
    notFound: "/404",
} as const;
