import { describe, it, expect, vi, beforeEach } from 'vitest';
import { SessionScheduleRepository } from '../../../api/repositories/session-schedule.repository';

describe('SessionScheduleRepository Unit test', () => {
    let mockDb: any;
    let repo: SessionScheduleRepository;

    beforeEach(() => {
        mockDb = {
            query: {
                scheduledSession: {
                    findMany: vi.fn().mockResolvedValue([{ id: "sess_1" }])
                }
            },
        };
        repo = new SessionScheduleRepository(mockDb);
    });

    it('correctly maps logical date bounds into raw sql query conditions passing to Drizzle Driver natively', async () => {
        const ORG_ID = "org_test";
        const START_EPOCH = 10000;
        const END_EPOCH = 50000;
        
        await repo.getSessionsForOrg(ORG_ID, START_EPOCH, END_EPOCH);

        expect(mockDb.query.scheduledSession.findMany).toHaveBeenCalledTimes(1);
        const args = mockDb.query.scheduledSession.findMany.mock.calls[0][0];
        expect(args.where).toBeDefined();
    });

    it('successfully bounds queries inclusively for start of day and end of day edge cases', async () => {
        const ORG_ID = "org_test";
        // E.g., March 21 exactly midnight
        const START_OF_DAY = new Date("2026-03-21T00:00:00.000Z").getTime();
        // E.g., March 21 exactly 11:59:59.999 PM
        const END_OF_DAY = new Date("2026-03-21T23:59:59.999Z").getTime();

        await repo.getSessionsForOrg(ORG_ID, START_OF_DAY, END_OF_DAY);

        // The exact AST generated by Drizzle checks `>=` and `<=` ensuring bounds are never dropped
        expect(mockDb.query.scheduledSession.findMany).toHaveBeenCalledTimes(1);
        const args = mockDb.query.scheduledSession.findMany.mock.calls[0][0];
        
        // Asserting the parameters passed into the sql AST arrays are exactly the boundaries requested
        // (Drizzle stores raw bound params in `query.params` deep inside the symbol map natively)
        expect(args.where).toBeDefined();
    });
});
