name: API CD

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test-entix-api
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: HUSKY=0 npm ci || (cat /home/runner/.npm/_logs/* && exit 1)

      - name: Lint code
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build project
        run: npm run build

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run tests
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test-entix-api
          PGUSER: postgres
          PGPASSWORD: postgres
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: test-entix-api
          PORT: 3000
          LOG_LEVEL: error
          COGNITO_REGION: us-east-1
          COGNITO_USER_POOL_ID: us-east-1_1234567890
          COGNITO_CLIENT_ID: 1234567890
        run: npm test
